/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testjni_example_com_testjni_myJNI */

#ifndef _Included_testjni_example_com_testjni_myJNI
#define _Included_testjni_example_com_testjni_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testjni_example_com_testjni_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_testjni_example_com_testjni_myJNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
